spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:test
    username: root
    password: test
logging:
  level:
    root: info
    xyz.mydev.orm.mybatisplus.example.mapper: debug
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: NONE
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false